#!/bin/sh

if ! hostname | grep -iq 'raspberry'; then
    return
fi

if command -v keychain >/dev/null 2>&1; then
    keychain --agents ssh --quiet
    if ls ~/.keychain/*-sh >/dev/null 2>&1; then
        # shellcheck source=/dev/null
        . ~/.keychain/*-sh
    fi
fi

if ! pgrep gpg-agent >/dev/null 2>&1; then
    GPG_TTY=$(tty)
    export GPG_TTY
    # shellcheck disable=SC2046
    eval $(gpg-agent --daemon)
fi
