#!/bin/bash

keychain --agents ssh &> /dev/null
# shellcheck source=/dev/null
source ~/.keychain/*-sh

ssh-add -l &> /dev/null || ssh-add "$HOME"/.ssh/*.key

GPG_TTY=$(tty)
export GPG_TTY
echo "Starting gpg-agent daemon"
# shellcheck disable=SC2046
eval $(gpg-agent --daemon)
