#!/bin/bash

# sudo apt install keychain

keychain --agents ssh &> /dev/null

# shellcheck source=/dev/null
source ~/.keychain/*-sh

GPG_TTY=$(tty)
export GPG_TTY

ssh-add -l &> /dev/null || ssh-add "$HOME"/.ssh/*.key
