#!/bin/bash

# sudo apt install keychain

keychain --agents ssh &> /dev/null

# shellcheck source=/dev/null
source ~/.keychain/*-sh

gpg_tty=$(tty)
export GPG_TTY=gpg_tty

ssh-add -l &> /dev/null || ssh-add "$HOME"/.ssh/*.key
