#!/bin/bash

if ! test -f "/opt/homebrew/opt/nvm/nvm.sh" ; then
    return
fi

export NVM_DIR="$HOME/.nvm"
# shellcheck source=/dev/null
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
# shellcheck source=/dev/null
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
