#!/bin/bash

# Only needed in powershell not needed in "Windows-terminal"
export LS_COLORS="ow=01;36;40"

export WINHOME="/mnt/c/Users/Jor"

# WSL doesn't start an ssh/key agent
keychain --agents ssh &> /dev/null 
# shellcheck source=/dev/null
source ~/.keychain/*-sh
 
